In [1]:
# ex1
import numpy as np

empty_array = np.empty(2, dtype=int)
zeros_array = np.zeros(5)
arange_array = np.arange(0, 10)
eye_matrix = np.eye(3)
randint_array = np.random.randint(1, 10, (3, 3))
rand_array = np.random.rand(2, 3)

print("empty_array:", empty_array)
print("zeros_array:", zeros_array)
print("arange_array:", arange_array)
print("eye_matrix:\n", eye_matrix)
print("randint_array:\n", randint_array)
print("rand_array:\n", rand_array)

empty_array: [              1 139908276617216]
zeros_array: [0. 0. 0. 0. 0.]
arange_array: [0 1 2 3 4 5 6 7 8 9]
eye_matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
randint_array:
 [[6 3 3]
 [1 2 3]
 [1 6 5]]
rand_array:
 [[0.2909652  0.16805838 0.9781288 ]
 [0.20400095 0.34210516 0.42036521]]


In [4]:
# ex2
import numpy as np

arr = np.array([1 , 2, 3, 4, 5])
print("arr :", arr)
print("Shape of arr:", arr.shape)
print("Size of arr:", arr.size)
print("Data type of arr :", arr.dtype)
print("Number of dimensions of arr:", arr.ndim)

arr : [1 2 3 4 5]
Shape of arr: (5,)
Size of arr: 5
Data type of arr : int64
Number of dimensions of arr: 1


In [6]:
# ex3
import numpy as np
arr1d = np.array([1 , 2, 3, 4, 5])
first_element = arr1d[0]
print("The first element of arr1d: ", first_element )
last_element = arr1d[-1]
print("The last element of arr1d: ",last_element )

The first element of arr1d:  1
The last element of arr1d:  5


In [7]:
# ex4
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
element_1_2 = arr2d[0, 1]
print(element_1_2 )

[[1 2 3]
 [4 5 6]]
2


In [8]:
# ex5
import numpy as np
arr1d = np.array ([1 , 2, 3, 4, 5])
slice_arr1d = arr1d[1:4]
print("arr1d:", arr1d )
print("Sclicing arr1d frome 1 to 3:",slice_arr1d)

arr1d: [1 2 3 4 5]
Sclicing arr1d frome 1 to 3: [2 3 4]


In [10]:
# ex6
import numpy as np
arr2d = np.array(
[[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
slice_arr2d = arr2d[1:3 , 1:]
print("arr2d:\n", arr2d )
print("Slicing arr2d from row 2 to row 3 and column 2 to column end:\n", slice_arr2d )

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing arr2d from row 2 to row 3 and column 2 to column end:
 [[5 6]
 [8 9]]


In [11]:
# ex7
import numpy as np
original_array = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
new_array = original_array.transpose()
print(new_array)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [12]:
# ex8
import numpy as np
original_array = np.array([[0, 1],
[2, 3],
[4, 5]])
new_array=np.reshape(original_array, (2,3))
print(new_array)

[[0 1 2]
 [3 4 5]]


In [14]:
# ex9
import numpy as np
arr_2D = np.array([[1 , 2, 3], [4, 5, 6]])
# (2, 3) ->(3, 2)
new_arr_2D = np.reshape(arr_2D , (3, 2))
# 2D -> 1D
arr_1D = np.reshape(arr_2D , newshape =(6 , ))
print("array 2D:\n", arr_2D , arr_2D.shape )
print("new array 2D :\n", new_arr_2D, new_arr_2D.shape)
print("array 1D:\n", arr_1D, arr_1D.shape)

array 2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
new array 2D :
 [[1 2]
 [3 4]
 [5 6]] (3, 2)
array 1D:
 [1 2 3 4 5 6] (6,)


In [ ]:
# ex10
import numpy as np
original_array = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
original_array.resize(3,4)
print(original_array)

In [ ]:
# ex11
import numpy as np
original_array = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
axis =0
axis =1
new_array1 = np.insert(original_array,0,[10,10,10],axis=0)
new_array2 = np.insert(original_array,3,[10,10,10],axis=0)
new_array3 = np.insert(original_array,0,[10,10,10],axis=1)
new_array4 = np.insert(original_array,3,[10,10,10],axis=1)

In [17]:
# ex12
import numpy as np
original_array1 = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

original_array2 = np.array([[10, 20, 30],
[40, 50, 60],
[70, 80, 90]])

new_array1 = np.append(original_array1,original_array2,axis=1)
new_array2 = np.append(original_array1,original_array2,axis=0)
print(new_array1)
print(new_array2)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
# ex13
import numpy as np
original_array = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

new_array1 = np.delete(original_array,0,axis=0)
new_array2 = np.delete(original_array,0,axis=1)
new_array3 = np.delete(original_array,2,axis=0)
new_array4 = np.delete(original_array,2,axis=1)
print(new_array1)
print(new_array2)
print(new_array3)
print(new_array4)

[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


In [19]:
# ex14
import numpy as np

a = np.array([
    [0, 1, 3],
    [5, 7, 9],
    [7, 8, 9]
])

b = np.array([
    [0, 2, 4],
    [6, 8, 10]
])

a_truncated = a[:2, :]

print(np.concatenate((a_truncated, b), axis=1))
print(np.hstack((a_truncated, b)))
print(np.vstack((a, b)))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
[[ 0  1  3]
 [ 5  7  9]
 [ 7  8  9]
 [ 0  2  4]
 [ 6  8 10]]


In [ ]:
# ex15
import numpy as np
arr_1 = np.array([1 , 2, 3])
arr_2 = np.array([4 , 5, 6])
arr_3 = np.hstack((arr_1 , arr_2))
print("arr 1:\n", arr_1)
print("arr 2:\n", arr_2)
print("Result_arr:\n", arr_3)

In [ ]:
# ex16
import numpy as np
arr_1 = np.array([1 , 2, 3])
arr_2 = np.array([4 , 5, 6])
arr_3 = np.vstack((arr_1 , arr_2))
print("arr 1:", arr_1)
print("arr 2:", arr_2)
print("Result_arr:\n", arr_3)

In [20]:
# ex17
import numpy as np
arr_1 = np.array([[1 , 2, 3],
[4, 5, 6]])
arr_2 = np.array([[7 , 8, 9],
[10 , 11, 12]])

arr_3 = np.concatenate((arr_1, arr_2),axis =0)
arr_4 = np.concatenate((arr_1, arr_2),axis =1)

[[1,2,3],
[4,5,6]]
print("Array 1:\n", arr_1)
print("Array 2:\n", arr_2)
print("Result( axis =0) :\n",arr_3)
print("Result( axis =1) :\n",arr_4)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Result( axis =0) :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Result( axis =1) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [21]:
# ex18
import numpy as np
# array 1D
arr_1 = np.array([1 , 2, 3])
# 1D -> 2D
arr_2 = arr_1[np.newaxis, :]

arr_3 = arr_2[np.newaxis, :, np.newaxis ,:, np.newaxis]
print("array 1: ", arr_1 , arr_1.shape)
print("array 2: ", arr_2 , arr_2.shape)
print("array 3:\n ", arr_3 , arr_3.shape)

array 1:  [1 2 3] (3,)
array 2:  [[1 2 3]] (1, 3)
array 3:
  [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [22]:
# ex19
import numpy as np
arr_1 = np.array([1 , 2, 3])
# 1D -> 2D
arr_2 = np.expand_dims(arr_1 , axis =0)

arr_3 = np.expand_dims(arr_2 ,axis =(0 , 2, 4))
print("array 1:", arr_1 , arr_1.shape)
print("array 2:", arr_2 , arr_2.shape)
print("array 3:\n", arr_3 , arr_3.shape)

array 1: [1 2 3] (3,)
array 2: [[1 2 3]] (1, 3)
array 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


In [23]:
# ex20
import numpy as np
arr2d = np. array ([[1 , 7, 3],
[10, 8, 6],
[5, 15, 9]])
print("Original array\n",arr2d)
sort_in_row = np.sort(arr2d , axis =1)
sort_in_col = np.sort(arr2d , axis =0)
print("Result by row:\n", sort_in_row)
print("Result by col:\n", sort_in_col)

Original array
 [[ 1  7  3]
 [10  8  6]
 [ 5 15  9]]
Result by row:
 [[ 1  3  7]
 [ 6  8 10]
 [ 5  9 15]]
Result by col:
 [[ 1  7  3]
 [ 5  8  6]
 [10 15  9]]


In [ ]:
# ex30
import numpy as np
a = np.array ([[0, 3, 1],
[3, 7, 5],
[6, 4, 8]])
b = [10, 5, 11]
print("Median value in row:", np.median(a , axis =1))
print("Median value in col:", np.median(a , axis =0))
print("Median array A:", np.median(a))
print("Median array B:", np.median(b))

In [25]:
# ex40
import numpy as np
import numpy.matlib
#with the specified shape and type without initializing entries
mat_e = np.matlib.empty((3, 2), dtype=int)
#filled with 0
mat_zeros =np.matlib.zeros((5, 3))
#filled with 1
mat_ones = np.matlib.ones((4,3))
#diagonal elements filled with 1, others with 0
mat_ones = np.matlib.eye(3,5)
#create square matrix with 0, diagonal filled with 1, others with 0
mat_zeros = np.matlib.identity(5)
#filled with random data
mat_e = np.matlib.empty((3, 2))
print(mat_e)
print(mat_zeros)
print(mat_ones)

[[5.e-324 0.e+000]
 [0.e+000 0.e+000]
 [0.e+000 0.e+000]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [27]:
# ex42
import numpy as np
a = np.array([1,2,3,4,5])
np.savetxt("out.txt", a)
b = np.loadtxt("out.txt")
print(b)


[1. 2. 3. 4. 5.]


In [28]:
# practice1
import numpy as np           # Nhập thư viện NumPy và đặt bí danh (alias) là 'np'

a = np.array([1, 2, 3])      # Khởi tạo một mảng 1 chiều (1D array) với các giá trị 1, 2, 3
print(type(a))               # In ra kiểu dữ liệu của biến 'a', kết quả là <class 'numpy.ndarray'>
print(a.shape)               # In ra hình dạng (shape) của mảng 'a', kết quả là (3,)
print(a[0], a[1], a[2])      # Truy cập và in ra các phần tử tại index 0, 1, và 2
a[0] = 5                     # Thay đổi giá trị của phần tử đầu tiên (index 0) thành 5
print(a)                     # In ra mảng 'a' sau khi đã thay đổi, kết quả là [5 2 3]

# --- Làm việc với Mảng 2 Chiều ---

b = np.array([[1,2,3],[4,5,6]]) # Khởi tạo một mảng 2 chiều (ma trận 2x3)
print(b.shape)                  # In ra hình dạng của ma trận 'b', kết quả là (2, 3) (2 hàng, 3 cột)
print(b[0, 0], b[0, 1], b[1, 0])# Truy cập và in ra các phần tử theo cú pháp [hàng, cột]:
                                # b[0, 0] = 1, b[0, 1] = 2, b[1, 0] = 4


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
# practice2
import numpy as np           # Nhập thư viện NumPy, đặt bí danh (alias) là 'np'

a = np.zeros((2,2))          # Tạo mảng 2x2, điền đầy bằng các số 0 (float)
b = np.ones((1,2))           # Tạo mảng 1x2, điền đầy bằng các số 1 (float)
c = np.full((2,2), 7)        # Tạo mảng 2x2, điền đầy bằng giá trị cố định là 7
d = np.eye(2)                # Tạo ma trận đơn vị (Identity Matrix) 2x2
e = np.random.random((2,2))  # Tạo mảng 2x2, điền đầy bằng các số thực ngẫu nhiên trong khoảng [0.0, 1.0)

In [ ]:
# practice3
import numpy as np                                # Nhập thư viện NumPy và đặt bí danh là 'np'

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # Tạo một ma trận 3x4 (3 hàng, 4 cột)
b = a[:2, 1:3]                                    # Cắt (slice) mảng 'a' để tạo ra 'b'. 'b' là một VIEW (tham chiếu) đến 2 hàng đầu tiên (0, 1) và cột 1, 2 của 'a'.
print(a[0, 1])                                    # In ra giá trị tại hàng 0, cột 1 của 'a'. Giá trị này là 2.
b[0, 0] = 77                                      # Thay đổi phần tử đầu tiên của 'b' thành 77. Vì 'b' là một view, thay đổi này cũng áp dụng cho 'a'.
                                                  # Phần tử b[0, 0] tương ứng với phần tử a[0, 1].
print(a[0, 1])                                    # In lại giá trị tại a[0, 1]. Kết quả bây giờ là 77 (do thay đổi thông qua 'b').

In [ ]:
# practice4
import numpy as np                                       # Nhập thư viện NumPy và đặt bí danh là 'np'

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])        # Tạo một ma trận 3x4

# --- Truy cập Hàng (Row Access) ---

row_r1 = a[1, :]                                        # Lấy hàng có chỉ mục 1 (hàng thứ hai). Kết quả là mảng 1 chiều (Rank 1).
row_r2 = a[1:2, :]                                      # Lấy hàng có chỉ mục 1 (hàng thứ hai) sử dụng slicing [1:2]. Kết quả là mảng 2 chiều (Rank 2).

print(row_r1, row_r1.shape)                             # In ra mảng row_r1 và hình dạng (shape) của nó. Kết quả: [5 6 7 8] (4,)
print(row_r2, row_r2.shape)                             # In ra mảng row_r2 và hình dạng (shape) của nó. Kết quả: [[5 6 7 8]] (1, 4)

# --- Truy cập Cột (Column Access) ---

col_r1 = a[:, 1]                                        # Lấy cột có chỉ mục 1 (cột thứ hai). Kết quả là mảng 1 chiều (Rank 1).
col_r2 = a[:, 1:2]                                      # Lấy cột có chỉ mục 1 (cột thứ hai) sử dụng slicing [1:2]. Kết quả là mảng 2 chiều (Rank 2).

print(col_r1, col_r1.shape)                             # In ra mảng col_r1 và hình dạng (shape) của nó. Kết quả: [ 2  6 10] (3,)
print(col_r2, col_r2.shape)                             # In ra mảng col_r2 và hình dạng (shape) của nó. Kết quả: [[ 2] [ 6] [10]] (3, 1)

In [ ]:
# practice5
import numpy as np                          # Nhập thư viện NumPy và đặt bí danh là 'np'

a = np.array([[1,2], [3, 4], [5, 6]])        # Tạo một ma trận 3x2 (3 hàng, 2 cột)

# --- Index Mảng Số Nguyên (Integer Array Indexing) ---

# Truy cập các phần tử tại các vị trí không liên tục: (hàng 0, cột 0), (hàng 1, cột 1), (hàng 2, cột 0)
# Kết quả là một mảng 1 chiều chứa các giá trị: [a[0, 0], a[1, 1], a[2, 0]]
print(a[[0, 1, 2], [0, 1, 0]])               # In ra: [1 4 5]

# Đây là cách thủ công để tạo ra cùng một kết quả trên (chỉ để so sánh và xác nhận)
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # In ra: [1 4 5]

# --- Index Mảng Số Nguyên để Lặp lại các Giá trị ---

# Truy cập các phần tử tại các vị trí: (hàng 0, cột 1) và (hàng 0, cột 1)
# Kết quả là một mảng 1 chiều chứa các giá trị: [a[0, 1], a[0, 1]]
print(a[[0, 0], [1, 1]])                     # In ra: [2 2]

# Đây là cách thủ công để tạo ra cùng một kết quả trên
print(np.array([a[0, 1], a[0, 1]]))          # In ra: [2 2]

In [ ]:
# practice6
import numpy as np                                       # Nhập thư viện NumPy và đặt bí danh là 'np'

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])   # Tạo ma trận 4x3 (4 hàng, 3 cột)
print(a)                                                 # In ra ma trận 'a' ban đầu

b = np.array([0, 2, 0, 1])                               # Tạo mảng 'b' chứa chỉ mục cột (column indices) cho mỗi hàng
                                                         # b[0]=0 (cột 0 cho hàng 0), b[1]=2 (cột 2 cho hàng 1), ...

# Sử dụng Index Mảng Số Nguyên để chọn các phần tử:
# Hàng được lấy từ np.arange(4) -> [0, 1, 2, 3]
# Cột được lấy từ b -> [0, 2, 0, 1]
# Các phần tử được chọn là: a[0, 0], a[1, 2], a[2, 0], a[3, 1]
print(a[np.arange(4), b])                                # In ra các phần tử được chọn: [1 6 7 11]

# Tăng giá trị của các phần tử được chọn thêm 10:
# a[0, 0] += 10, a[1, 2] += 10, a[2, 0] += 10, a[3, 1] += 10
a[np.arange(4), b] += 10                                 # Thực hiện phép cộng
print(a)                                                 # In ra ma trận 'a' sau khi đã sửa đổi

In [ ]:
# practice7
import numpy as np                          # Nhập thư viện NumPy và đặt bí danh là 'np'

a = np.array([[1,2], [3, 4], [5, 6]])        # Tạo một ma trận 3x2

bool_idx = (a > 2)                          # Tạo một mảng Boolean (boolean mask) cùng kích thước với 'a'.
                                            # Mỗi phần tử là True nếu phần tử tương ứng trong 'a' lớn hơn 2, ngược lại là False.

print(bool_idx)                             # In ra mảng Boolean mask:
                                            # [[False, False],
                                            #  [ True,  True],
                                            #  [ True,  True]]

# Sử dụng mảng Boolean mask để chọn các phần tử tương ứng là True trong 'a'.
# Kết quả luôn là một mảng 1 chiều chứa các giá trị được chọn.
print(a[bool_idx])                          # In ra các phần tử được chọn: [3 4 5 6]

# Cách viết rút gọn, tạo mask và áp dụng nó ngay lập tức
print(a[a > 2])                             # In ra cùng các phần tử được chọn: [3 4 5 6]

In [ ]:
# practice8
import numpy as np                          # Nhập thư viện NumPy và đặt bí danh là 'np'

# --- Trường hợp 1: Số nguyên (Integer) mặc định ---
x = np.array([1, 2])                        # Tạo một mảng từ danh sách các số nguyên.
                                            # NumPy thường chọn kiểu số nguyên mặc định (ví dụ: int32 hoặc int64).
print(x.dtype)                              # In ra kiểu dữ liệu của 'x'. Kết quả thường là 'int64' (tùy thuộc vào hệ thống).

# --- Trường hợp 2: Số thực (Float) mặc định ---
x = np.array([1.0, 2.0])                    # Tạo một mảng từ danh sách các số thực (có dấu chấm thập phân).
                                            # NumPy mặc định chọn kiểu số thực float.
print(x.dtype)                              # In ra kiểu dữ liệu của 'x'. Kết quả thường là 'float64'.

# --- Trường hợp 3: Ép buộc kiểu dữ liệu tường minh ---
x = np.array([1, 2], dtype=np.int64)        # Tạo một mảng và ép buộc kiểu dữ liệu là số nguyên 64-bit.
print(x.dtype)                              # In ra kiểu dữ liệu của 'x'. Kết quả là 'int64'.

In [ ]:
# practice9
import numpy as np                                   # Nhập thư viện NumPy và đặt bí danh là 'np'

# Khởi tạo hai mảng 2x2 kiểu float64
x = np.array([[1,2],[3,4]], dtype=np.float64)        # Mảng x: [[1.0, 2.0], [3.0, 4.0]]
y = np.array([[5,6],[7,8]], dtype=np.float64)        # Mảng y: [[5.0, 6.0], [7.0, 8.0]]

# --- Phép Cộng (Addition) ---
# Thực hiện cộng từng phần tử (element-wise): x[i, j] + y[i, j]
print(x + y)                                         # Sử dụng toán tử: [[6.0, 8.0], [10.0, 12.0]]
print(np.add(x, y))                                  # Sử dụng hàm NumPy: [[6.0, 8.0], [10.0, 12.0]]

# --- Phép Trừ (Subtraction) ---
# Thực hiện trừ từng phần tử: x[i, j] - y[i, j]
print(x - y)                                         # Sử dụng toán tử: [[-4.0, -4.0], [-4.0, -4.0]]
print(np.subtract(x, y))                             # Sử dụng hàm NumPy: [[-4.0, -4.0], [-4.0, -4.0]]

# --- Phép Nhân (Multiplication) ---
# Thực hiện nhân từng phần tử (KHÔNG phải nhân ma trận): x[i, j] * y[i, j]
print(x * y)                                         # Sử dụng toán tử: [[5.0, 12.0], [21.0, 32.0]]
print(np.multiply(x, y))                             # Sử dụng hàm NumPy: [[5.0, 12.0], [21.0, 32.0]]

# --- Phép Chia (Division) ---
# Thực hiện chia từng phần tử: x[i, j] / y[i, j]
print(x / y)                                         # Sử dụng toán tử: [[0.2, 0.333...], [0.428..., 0.5]]
print(np.divide(x, y))                               # Sử dụng hàm NumPy: [[0.2, 0.333...], [0.428..., 0.5]]

# --- Hàm Toán Học Đơn Khối (Unary Function) ---
# Tính căn bậc hai của từng phần tử trong x
print(np.sqrt(x))                                    # Tính căn bậc hai: [[1.0, 1.414...], [1.732..., 2.0]]

In [29]:
# practice15
import numpy as np                                   # Nhập thư viện NumPy và đặt bí danh là 'np'

v = np.array([1,2,3])                                # Tạo mảng 1D (shape (3,))
w = np.array([4,5])                                  # Tạo mảng 1D (shape (2,))

# --- Ví dụ 1: Nhân ma trận 3x1 với mảng 1x2 (Broadcasting) ---
# np.reshape(v, (3, 1)) biến v thành ma trận 3x1: [[1], [2], [3]]
# Ma trận 3x1 được phát sóng (broadcast) để khớp với ma trận 1x2 (w)
# Kết quả là một ma trận 3x2, thực hiện phép nhân element-wise:
# [[1*4, 1*5], [2*4, 2*5], [3*4, 3*5]]
print(np.reshape(v, (3, 1)) * w)                     # In ra: [[ 4,  5], [ 8, 10], [12, 15]]

# --- Ví dụ 2: Cộng ma trận 2x3 với mảng 1D 3 phần tử (Broadcasting) ---
x = np.array([[1,2,3], [4,5,6]])                     # Tạo ma trận 2x3
# x (2, 3) + v (3,) => v được phát sóng dọc theo trục thứ 0 (trên 2 hàng)
# Từng hàng của x được cộng với toàn bộ mảng v.
print(x + v)                                         # In ra: [[2, 4, 6], [5, 7, 9]]

# --- Ví dụ 3: Phát sóng sau khi chuyển vị (Transpose) ---
# x.T (3, 2) + w (2,) => w được phát sóng dọc theo 3 cột của x.T
# (x.T + w) kết quả có shape (3, 2). Sau đó, chuyển vị (transpose) lần nữa.
print((x.T + w).T)                                   # In ra: [[5, 7, 9], [8, 10, 12]]

# --- Ví dụ 4: Cộng ma trận 2x3 với mảng cột 2x1 (Broadcasting) ---
# np.reshape(w, (2, 1)) biến w thành ma trận 2x1: [[4], [5]]
# x (2, 3) + w_reshaped (2, 1) => w_reshaped được phát sóng trên 3 cột của x
# Từng cột của x được cộng với toàn bộ mảng w_reshaped.
print(x + np.reshape(w, (2, 1)))                     # In ra: [[5, 6, 7], [9, 10, 11]]

# --- Ví dụ 5: Nhân ma trận với vô hướng (Scalar Multiplication) ---
# Số vô hướng (scalar) 2 được phát sóng để nhân với mọi phần tử của x.
print(x * 2)                                         # In ra: [[ 2,  4,  6], [ 8, 10, 12]]

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
